Read data remove species

In [ ]:
import pandas as pd

df = pd.read_csv('archive\Iris.csv')
df = df.drop(columns=['Species'])
df.to_csv('Iris_no_species.csv', index=False)

<>:4: SyntaxWarning: invalid escape sequence '\I'
<>:4: SyntaxWarning: invalid escape sequence '\I'
C:\Users\SMART TECH\AppData\Local\Temp\ipykernel_12884\2114415264.py:4: SyntaxWarning: invalid escape sequence '\I'
  df = pd.read_csv('archive\Iris.csv')


read data save in pd

In [3]:
import pandas as pd
df = pd.read_csv('Iris_no_species.csv')
df.tail(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

K_mean_algo

In [14]:
import random
import numpy as np

def initialize_centroids(data, k):
    centroids = np.mean(data, axis=0) + np.random.randn(k, data.shape[1])  # Initialize around mean with noise
    return np.array(centroids)

def assign_clusters(data, centroids):
    labels = []
    for point in data:
        distances = []
        for centroid in centroids:
            distance = sum((point - centroid) ** 2)  # Euclidean distance squared
            distances.append(distance)
        labels.append(distances.index(min(distances)))  # Assign nearest cluster
    return np.array(labels)

def update_centroids(data, labels, k):
    new_centroids = []
    for i in range(k):
        cluster_points = [data[j] for j in range(len(data)) if labels[j] == i]
        if cluster_points:
            new_centroid = np.mean(cluster_points, axis=0)  # Average of cluster points
        else:
            new_centroid = np.mean(data, axis=0)  # Reassign with overall mean
        new_centroids.append(new_centroid)
    return np.array(new_centroids)

def k_means(data, k, max_iters=50):
    centroids = initialize_centroids(data, k)
    iter=0
    for _ in range(max_iters):
        labels = assign_clusters(data, centroids)
        new_centroids = update_centroids(data, labels, k)
        if np.array_equal(centroids, new_centroids):
            break
        centroids = new_centroids
        iter+=1
    return centroids, labels, iter
data = df.drop(columns=['Id']).values
centroids, labels, iter = k_means(data, k=3)
print("Centroids:\n", centroids)
print("Labels:\n", labels)
print("Iterations:", iter)

Centroids:
 [[5.006      3.418      1.464      0.244     ]
 [5.88360656 2.74098361 4.38852459 1.43442623]
 [6.85384615 3.07692308 5.71538462 2.05384615]]
Labels:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 2 2 2 1 2 2 2 2
 2 2 1 1 2 2 2 2 1 2 1 2 1 2 2 1 1 2 2 2 2 2 1 2 2 2 2 1 2 2 2 1 2 2 2 1 2
 2 1]
Iterations: 4


By using Siket-learn

In [16]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(data)
print(kmeans.cluster_centers_)
print(kmeans.labels_)
print(kmeans.n_iter_)


[[6.85384615 3.07692308 5.71538462 2.05384615]
 [5.006      3.418      1.464      0.244     ]
 [5.88360656 2.74098361 4.38852459 1.43442623]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 0 0 0 0 2 0 0 0 0
 0 0 2 2 0 0 0 0 2 0 2 0 2 0 0 2 2 0 0 0 0 0 2 0 0 0 0 2 0 0 0 2 0 0 0 2 0
 0 2]
12
